### ISSUE TITLE
Bigger Issue

### ISSUE THREAD

**Issue by lmf-git** [AnIdiotsGuide/guidebot#116]
Dear comrade,

Based on our earlier misfortunate interaction, although you expressed a serious lack of any respect or any love for me I wanted to point something out for your own benefit.

Your hairdresser has appeared to have missed a bit and cut the back of dein kopf unevenly.

Please don't swear at people, and get a bowl on this.

Farewell, my friend.

![Screenshot 2020-09-24 at 23 33 04](https://user-images.githubusercontent.com/67340984/94207016-a1cc8d00-febe-11ea-93bb-d3a283f4d64a.png)

**Comment by YorkAARGH** [comment]
How about you get off this repo with the personal attacks and insults.

**Comment by eslachance** [comment]
Awww someone got butthurt that we didn't allow them to advertise their crappy guild.
